# Generated by Django 4.2.7 on 2023-11-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('aut_id', models.AutoField(primary_key=True, serialize=False)),
                ('aut_author', models.CharField(max_length=50)),
                ('aut_year_born', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('book_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_name', models.CharField(max_length=50)),
                ('pub_company_name', models.CharField(max_length=255)),
                ('pub_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookAuthor_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.author')),
                ('BookAuthor_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.publisher'),
        ),
    ]
