# Generated by Django 4.2.7 on 2023-11-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_quantite',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.book')),
            ],
        ),
    ]
