# Generated by Django 4.2.7 on 2023-11-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_book_book_quantite_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nom', models.CharField(max_length=50)),
                ('usr_prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.user'),
            preserve_default=False,
        ),
    ]
